site_name: TTCal
repo_url: https://github.com/mweastwood/TTCal.jl
site_description: A calibration routine developed for the OVRO LWA.
site_author: Michael Eastwood

markdown_extensions:
    - math
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - mathjaxhelper.js

pages:
    - Home: index.md
    - Usage:
        - Gain Calibration: gaincal.md
        - Polarization Calibration: polcal.md
        - Amplitude Calibration: ampcal.md
        - Sky Models: sources.md
    - Developer Documentation:
        - API: external.md
        - Internal Documentation: internal.md
        - Contributing: contributing.md
        - Building this Website: docs.md
theme: readthedocs

